// 🤖 AUTO-GENERATED - DO NOT EDIT
// Generated by: scripts/build.ts
// Last updated: 2025-12-21T12:46:07.530Z

import onboardingHttp from '@/modules/onboarding/http';
import practiceHttp from '@/modules/practice/http';
import practiceClientIntakesHttp from '@/modules/practice-client-intakes/http';
import publicHttp from '@/modules/public/http';
import subscriptionsHttp from '@/modules/subscriptions/http';
import userDetailsHttp from '@/modules/user-details/http';

export const MODULE_REGISTRY = [
  { name: 'onboarding', http: onboardingHttp },
  { name: 'practice', http: practiceHttp },
  { name: 'practice-client-intakes', http: practiceClientIntakesHttp },
  { name: 'public', http: publicHttp },
  { name: 'subscriptions', http: subscriptionsHttp },
  { name: 'user-details', http: userDetailsHttp }
] as const;

export type ModuleName = typeof MODULE_REGISTRY[number]['name'];
