// 🤖 AUTO-GENERATED - DO NOT EDIT
// Generated by: scripts/build.ts
// Last updated: 2025-12-09T05:59:07.150Z

import intakePaymentsHttp from '@/modules/intake-payments/http';
import onboardingHttp from '@/modules/onboarding/http';
import practiceHttp from '@/modules/practice/http';
import publicHttp from '@/modules/public/http';
import subscriptionsHttp from '@/modules/subscriptions/http';
import userDetailsHttp from '@/modules/user-details/http';

export const MODULE_REGISTRY = [
  { name: 'intake-payments', http: intakePaymentsHttp },
  { name: 'onboarding', http: onboardingHttp },
  { name: 'practice', http: practiceHttp },
  { name: 'public', http: publicHttp },
  { name: 'subscriptions', http: subscriptionsHttp },
  { name: 'user-details', http: userDetailsHttp }
] as const;

export type ModuleName = typeof MODULE_REGISTRY[number]['name'];
