/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 *
 * This file is automatically generated by: pnpm run schemas:sync
 * It exports all schema files from modules and shared directories.
 *
 * To add a new schema:
 * 1. Create a new *.schema.ts file in your module
 * 2. Run: pnpm run schemas:sync
 *
 * Last updated: 2025-10-21T15:54:05.910Z
 */

// Better Auth core schemas (users, sessions, organizations, etc.)
export * from './better-auth-schema';

// Auto-discovered schemas from modules and shared directories
export * from './../modules/onboarding/schemas/onboarding.schema';
export * from './../modules/payments/database/schema/payment-intents.schema';
export * from './../modules/payments/database/schema/payment-links.schema';
export * from './../modules/practice/database/schema/practice.schema';
export * from './../shared/events/schemas/events.schema';
export * from './../shared/schemas/stripe.webhook-events.schema';
